database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/noisy?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  user: noisy
  password: 9Bop73T
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
server:
    applicationContextPath: /noisy